package com.dynamo.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "user")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Name")
    private String name;
    @DynamoDBAttribute(attributeName = "Email")
    private String email;
    @DynamoDBAttribute(attributeName = "Phone")
    private String phone;
    @DynamoDBAttribute(attributeName = "Address")
    private String address;
}
